<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="WithinTolerance" Id="{b9c242fe-198a-4c23-ab60-1ac81842e68f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION WithinTolerance : BOOL
VAR_INPUT
	v1 : LREAL;
	v2 : LREAL;
	tolerance : LREAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[WithinTolerance := ABS(v1-v2) < tolerance;]]></ST>
    </Implementation>
    <LineIds Name="WithinTolerance">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>