<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="CallHardwareModules" Id="{d53bfde7-ef31-4033-a59e-17a8585cdf25}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION CallHardwareModules : BOOL //only purpose of this function is to call modules from Hardware]]></Declaration>
    <Implementation>
      <ST><![CDATA[robotLeft();	
robotRight();

skidLeft();
skidRight();

magazineLeft();
magazineRight();

wrapper();
benderLeft();

horizontalDriveLeft();
horizontalDriveRight();

verticalDriveLeft();
verticalDriveRight();

insertionBottom();]]></ST>
    </Implementation>
    <LineIds Name="CallHardwareModules">
      <LineId Id="8" Count="4" />
      <LineId Id="19" Count="2" />
      <LineId Id="25" Count="1" />
      <LineId Id="56" Count="0" />
      <LineId Id="33" Count="1" />
      <LineId Id="36" Count="0" />
      <LineId Id="38" Count="1" />
      <LineId Id="37" Count="0" />
      <LineId Id="40" Count="0" />
      <LineId Id="30" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>