<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="CallHardwareModules" Id="{d53bfde7-ef31-4033-a59e-17a8585cdf25}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION CallHardwareModules : BOOL //only purpose of this function is to call modules from Hardware]]></Declaration>
    <Implementation>
      <ST><![CDATA[robot3();	
robot4();

skidA22Left();
skidA22Right();

magazineA22Left();
magazineA22Right();

wrapperA22();
benderA22Left();

horizontalDriveA22Left();
horizontalDriveA22Right();

verticalDriveA22Left();
verticalDriveA22Right();

pistonA22Bottom();]]></ST>
    </Implementation>
    <LineIds Name="CallHardwareModules">
      <LineId Id="57" Count="17" />
      <LineId Id="30" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>