<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="CallHardwareModules" Id="{d53bfde7-ef31-4033-a59e-17a8585cdf25}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION CallHardwareModules : BOOL]]></Declaration>
    <Implementation>
      <ST><![CDATA[robotLeft();
robotRight();

skidLeft();
skidRight();

stagingTableLeft();
stagingTableRight();

skidLeft();
skidRight();

magazineLeft();
magazineRight();

stagingTableLeft();
stagingTableRight();

strapper();

insertionLeft();
insertionRight();
insertionBottom();

stagingTemplateLeft();
stagingTemplateRight();]]></ST>
    </Implementation>
    <LineIds Name="CallHardwareModules">
      <LineId Id="8" Count="24" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>