<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="A_ContinuousDrive" Id="{0abc7204-321d-448b-a2d6-f81a2f9d40da}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT A_ContinuousDrive //generic drive that can only traverse in either direction or stop
VAR_INPUT
	bEnable : BOOL;
END_VAR
VAR_OUTPUT
	contact AT %I* : BOOL;
	
	outerLimit AT %I* : BOOL;
	home AT %I* : BOOL;
	innerLimit AT %I* : BOOL;
	
	homeSet : BOOL;
	busy : BOOL;
	error : BOOL;
END_VAR
VAR
	step : Homing;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="homingSequence" Id="{aeec6ab2-d9e1-4729-85e6-30d35385fa84}">
      <Declaration><![CDATA[METHOD ABSTRACT homingSequence : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="moveContinuous" Id="{5dab9c49-79fc-4eda-ae89-86f7ebf23aa2}">
      <Declaration><![CDATA[METHOD ABSTRACT moveContinuous : BOOL
VAR_INPUT
	direction : MC_Direction;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="stop" Id="{3650c7e9-87dd-4a3a-8c61-5eec42a10cce}">
      <Declaration><![CDATA[METHOD ABSTRACT stop : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="A_ContinuousDrive">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="A_ContinuousDrive.homingSequence">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="A_ContinuousDrive.moveContinuous">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="A_ContinuousDrive.stop">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>