<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="A_EncodedDrive" Id="{1454b08a-a9b0-4cb0-b21d-36cd618e7692}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT A_EncodedDrive //generic drive that can store a position
VAR_INPUT
	bEnable : BOOL;
END_VAR
VAR_OUTPUT
	contact AT %I* : BOOL;
	
	outerLimit AT %I* : BOOL;
	home AT %I* : BOOL;
	innerLimit AT %I* : BOOL;
	
	homeSet : BOOL;
	busy : BOOL;
	error : BOOL;
	
	position : LREAL;
	targetPos : LREAL;
END_VAR
VAR
	step : Homing;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="homingSequence" Id="{7e8a9954-f665-4d24-b985-a49016401870}">
      <Declaration><![CDATA[METHOD ABSTRACT homingSequence : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="moveAbsolute" Id="{d593af58-bfcd-43b4-8602-4fe761101a07}">
      <Declaration><![CDATA[METHOD ABSTRACT moveAbsolute : BOOL
VAR_INPUT
	newTarget : LREAL; 
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="moveContinuous" Id="{6ae786e1-99ef-4f1e-93f3-3f3be7b4f9da}">
      <Declaration><![CDATA[METHOD ABSTRACT moveContinuous : BOOL
VAR_INPUT
	direction : MC_Direction;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="moveRelative" Id="{70ed1220-645b-452f-9ed4-20ecaed4defd}">
      <Declaration><![CDATA[METHOD ABSTRACT moveRelative : BOOL
VAR_INPUT
	distance : LREAL;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="stop" Id="{7d7f1351-1fd5-453c-8624-d07b474730d6}">
      <Declaration><![CDATA[METHOD ABSTRACT stop : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="A_EncodedDrive">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="A_EncodedDrive.homingSequence">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="A_EncodedDrive.moveAbsolute">
      <LineId Id="6" Count="0" />
    </LineIds>
    <LineIds Name="A_EncodedDrive.moveContinuous">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="A_EncodedDrive.moveRelative">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="A_EncodedDrive.stop">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>