<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Drive" Id="{ec3a268c-7b78-4059-9d0f-ff73392242ce}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT Drive
VAR_INPUT
	bEnable : BOOL;	
END_VAR
VAR_OUTPUT
	home AT %I* : BOOL;
	outerLimit AT %I* : BOOL;
	innerLimit AT %I* : BOOL;
	
	homeSet : BOOL;
	busy : BOOL;
	error : BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Drive">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>