<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="WithinTolerance" Id="{70d5a386-b333-45cf-9af1-a80becc50e58}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION WithinTolerance : BOOL
VAR_INPUT
	value : LREAL;
	target : LREAL;
	tolerance : LREAL;
END_VAR
(*
checks if value is close enough to target within a given margin
*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[WithinTolerance := ABS(value-target) < tolerance;]]></ST>
    </Implementation>
    <LineIds Name="WithinTolerance">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>