<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{7f75ad39-54f6-4bc3-bace-5045f4922cc8}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	conveyor : ConveyorSC_NC;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>