<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="CarCorEx" Id="{43a9c6e1-e77d-41f5-aea3-07b47a57c140}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK CarCorEx
VAR_IN_OUT
	benderLeft : FoldingMachine;
	
	robotLeft, robotRight : RobotA22;
	
	skidLeft, skidRight : SkidMagazine;
	magazineLeft, magazineRight : SkidMagazine;
	
	wrapper : WrapMachine;
	
	horizontalDriveLeft, horizontalDriveRight : ServoNC;
	verticalDriveLeft, verticalDriveRight : ClearLinkMC;
	pistonBottom : SimplePiston;
	
	suctionTopLeft : ARRAY[*] OF SuctionPad; (*1..3*)
	suctionTopRight : ARRAY[*] OF SuctionPad; (*1..3*)
	suctionBottomLeft : ARRAY[*] OF SuctionPad; (*1..3*)
	suctionBottomRight : ARRAY[*] OF SuctionPad; (*1..3*)
	
	suctionBottom : ARRAY[*] OF SuctionPad; (*1..2*)
END_VAR
VAR_OUTPUT //controls
	pmlModeRequest : E_PMLProtectedUnitMode := ePMLProtUnitMode_Production;
	pmlMode : E_PMLProtectedUnitMode;
	
	pmlState : E_PMLState;
	pmlCommand : E_PMLCommand;

	stop : BOOL;
	execute : BOOL;
	hold : BOOL;
	reset : BOOL;
	
	done : BOOL;
	error : BOOL;
END_VAR
VAR
	pmlModeString : STRING;
	pmlStateString : STRING;
	
	pmlStateMachine : PML_StateMachine;
	pmlSemiAutoConfig : PML_UnitModeConfig;
	pmlModeManager : PML_UnitModeManager;
	
	step : (IDLE, LOAD_CORNERS, LOAD_FLATS, PUSH, TARGET_WRAP_POSITION, WRAP_AND_RELEASE, COMPLETE := 1050);
	iPair : INT;
	
	masterLoadStep : INT;
	loadStepLeft, loadStepRight : INT;
	
	iWrap : INT;
	wrapPoints : INT;
	wrapRotations : INT;
	masterLength : INT;
	
	releaseDelayTimer : TON;
END_VAR
VAR //local types
	topLeftFoldsArr, topRightFoldsArr, bottomLeftFoldsArr, bottomRightFoldsArr : ARRAY[0..GVL.maxPairs] OF INT;
	materialsArr : ARRAY[0..GVL.maxPairs] OF PositionMaterials := [
		(
			position := 0,
			top := 'CAR20M',
			left := 'CAR20S',
			right := 'CAR20S',
			bottom := 'CAR20L',
			topLeft := 'CAR28M',
			topRight := 'CAR28S',
			bottomLeft := 'CAR28S',
			bottomRight := 'CAR28L',
			wrapPoints := 1,
			wrapRotations := 4
		),
		(
			position := 0,
			topLeft := 'COR48',
			topRight := 'COR48',
			bottomLeft := 'COR48',
			bottomRight := 'COR48'
		)];
	
	demoHeight : REAL := 640; //mm
	
	insertionLeft, insertionRight : Insertion;
	innerLoadedMaterials, outerLoadedMaterials : ARRAY[Surface.TOP..Surface.BOTTOM_RIGHT] OF STRING;
	//inner: cardboard by default
	//outer: corner guard by default
END_VAR
VAR CONSTANT
	sectionID : SectionEnum := SectionEnum.CARDBOARD_CORNERGUARD;
	releaseDelay : TIME := T#2000MS;
END_VAR
VAR
	//AOIs encapsulate functionality and reduce the number of module variables
	aoiCornerGuardLeft, aoiCornerGuardRight : AOI_LoadCornerGuard;
	aoiCornerCardboardLeft, aoiCornerCardboardRight : AOI_LoadCornerCardboard;
	aoiFlatCardboardLeft, aoiFlatCardboardRight : AOI_LoadFlatCardboard;
	
	//for testing only
	latchLeft, latchRight : BOOL; //prevents sliders from overshooting the inner limit sensor
	suctionEnableTopLeft, suctionEnableTopRight, suctionEnableBottomLeft, suctionEnableBottomRight : BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[callLocalModules();

blocks();

configPML();
runPML();
(*
IF stop THEN //may need to turn off suction
	stopSequence();
	RETURN;
END_IF

IF NOT insertionLeft.homingComplete OR NOT insertionRight.homingComplete THEN
	homingSequence();
	RETURN;
END_IF
*)]]></ST>
    </Implementation>
    <Folder Name="Actions" Id="{c8c39f76-dbed-4e64-98b8-9f897e55ef48}" />
    <Folder Name="Corner Cardboard" Id="{ae97f731-8159-458d-a4c2-1a1c4ac5d0d1}" />
    <Folder Name="Corner Guards" Id="{1633509f-8083-40cb-8029-83f401dfca46}" />
    <Folder Name="Flat Cardboard" Id="{ccd7d2aa-e76b-439c-81f7-22b0db1787fb}" />
    <Folder Name="PML Inter. States" Id="{bb7e80d1-aaba-45a3-942d-4c0ae1b7e0a1}" />
    <Action Name="blocks" Id="{42a09ab4-5795-4272-b1bf-07353ead9a10}" FolderPath="Actions\">
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Ld"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeBox">
                      <o>
                        <v n="BoxType">"AOI_LoadCornerGuard"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"aoiCornerGuardLeft"</v>
                          <v n="Type">"AOI_LoadCornerGuard"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">138L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">140L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">141L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">142L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">143L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">144L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"INT"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">145L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">true</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"TRUE"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">147L</v>
                            </o>
                            <v n="Id">146L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">149L</v>
                            </o>
                            <v n="Id">148L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"sectionID"</v>
                              <v n="Type">"SectionEnum"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">151L</v>
                            </o>
                            <v n="Id">150L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"robotLeft"</v>
                              <v n="Type">"RobotA22"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">153L</v>
                            </o>
                            <v n="Id">152L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"magazineLeft"</v>
                              <v n="Type">"SkidMagazine"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">155L</v>
                            </o>
                            <v n="Id">154L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"innerLoadedMaterials"</v>
                              <v n="Type">"ARRAY [Surface.TOP..Surface.BOTTOM_RIGHT] OF STRING"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">157L</v>
                            </o>
                            <v n="Id">156L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <v n="Type">"Surface"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">159L</v>
                            </o>
                            <v n="Id">158L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <v n="Type">"STRING"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">161L</v>
                            </o>
                            <v n="Id">160L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <v n="Type">"POINTER TO SuctionPad"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">163L</v>
                            </o>
                            <v n="Id">162L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <v n="Type">"DINT"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">165L</v>
                            </o>
                            <v n="Id">164L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>EN</v>
                            <v>execute</v>
                            <v>sectionID</v>
                            <v>robot</v>
                            <v>magazine</v>
                            <v>loadedMaterials</v>
                            <v>surfaceID</v>
                            <v>material</v>
                            <v>suctions</v>
                            <v>numPads</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>SectionEnum[REF]</v>
                            <v>RobotA22[REF]</v>
                            <v>SkidMagazine[REF]</v>
                            <v>POINTER TO STRING</v>
                            <v>Surface</v>
                            <v>STRING</v>
                            <v>POINTER TO SuctionPad</v>
                            <v>DINT</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>ENO</v>
                            <v>donePulse</v>
                            <v>done</v>
                            <v>busy</v>
                            <v>error</v>
                            <v>recovery</v>
                            <v>failCounter</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>INT</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <v n="EN">true</v>
                        <v n="ENO">true</v>
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">139L</v>
                      </o>
                      <o>
                        <v n="BoxType">"AOI_LoadCornerGuard"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"aoiCornerGuardRight"</v>
                          <v n="Type">"AOI_LoadCornerGuard"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">166L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">168L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">169L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">170L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">171L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">172L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"INT"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">173L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">true</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"TRUE"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">175L</v>
                            </o>
                            <v n="Id">174L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">177L</v>
                            </o>
                            <v n="Id">176L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"sectionID"</v>
                              <v n="Type">"SectionEnum"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">179L</v>
                            </o>
                            <v n="Id">178L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"robotRight"</v>
                              <v n="Type">"RobotA22"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">181L</v>
                            </o>
                            <v n="Id">180L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"magazineRight"</v>
                              <v n="Type">"SkidMagazine"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">183L</v>
                            </o>
                            <v n="Id">182L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"innerLoadedMaterials"</v>
                              <v n="Type">"ARRAY [Surface.TOP..Surface.BOTTOM_RIGHT] OF STRING"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">185L</v>
                            </o>
                            <v n="Id">184L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <v n="Type">"Surface"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">187L</v>
                            </o>
                            <v n="Id">186L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <v n="Type">"STRING"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">189L</v>
                            </o>
                            <v n="Id">188L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <v n="Type">"POINTER TO SuctionPad"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">191L</v>
                            </o>
                            <v n="Id">190L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <v n="Type">"DINT"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">193L</v>
                            </o>
                            <v n="Id">192L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>EN</v>
                            <v>execute</v>
                            <v>sectionID</v>
                            <v>robot</v>
                            <v>magazine</v>
                            <v>loadedMaterials</v>
                            <v>surfaceID</v>
                            <v>material</v>
                            <v>suctions</v>
                            <v>numPads</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>SectionEnum[REF]</v>
                            <v>RobotA22[REF]</v>
                            <v>SkidMagazine[REF]</v>
                            <v>POINTER TO STRING</v>
                            <v>Surface</v>
                            <v>STRING</v>
                            <v>POINTER TO SuctionPad</v>
                            <v>DINT</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>ENO</v>
                            <v>donePulse</v>
                            <v>done</v>
                            <v>busy</v>
                            <v>error</v>
                            <v>recovery</v>
                            <v>failCounter</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>INT</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <v n="EN">true</v>
                        <v n="ENO">true</v>
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">167L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">137L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeBox">
                      <o>
                        <v n="BoxType">"AOI_LoadFlatCardboard"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"aoiFlatCardboardLeft"</v>
                          <v n="Type">"AOI_LoadFlatCardboard"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">200L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">29L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">36L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">37L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">38L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">39L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"INT"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">40L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">true</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"TRUE"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">10L</v>
                            </o>
                            <v n="Id">9L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">31L</v>
                            </o>
                            <v n="Id">30L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"sectionID"</v>
                              <v n="Type">"SectionEnum"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">33L</v>
                            </o>
                            <v n="Id">32L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"robotLeft"</v>
                              <v n="Type">"RobotA22"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">42L</v>
                            </o>
                            <v n="Id">41L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"skidLeft"</v>
                              <v n="Type">"SkidMagazine"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">44L</v>
                            </o>
                            <v n="Id">43L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"outerLoadedMaterials"</v>
                              <v n="Type">"ARRAY [Surface.TOP..Surface.BOTTOM_RIGHT] OF STRING"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">46L</v>
                            </o>
                            <v n="Id">45L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <v n="Type">"Surface"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">48L</v>
                            </o>
                            <v n="Id">47L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <v n="Type">"STRING"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">50L</v>
                            </o>
                            <v n="Id">49L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <v n="Type">"POINTER TO SuctionPad"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">52L</v>
                            </o>
                            <v n="Id">51L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <v n="Type">"DINT"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">54L</v>
                            </o>
                            <v n="Id">53L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>EN</v>
                            <v>execute</v>
                            <v>sectionID</v>
                            <v>robot</v>
                            <v>skid</v>
                            <v>loadedMaterials</v>
                            <v>surfaceID</v>
                            <v>material</v>
                            <v>suctions</v>
                            <v>numPads</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>SectionEnum[REF]</v>
                            <v>RobotA22[REF]</v>
                            <v>SkidMagazine[REF]</v>
                            <v>POINTER TO STRING</v>
                            <v>Surface</v>
                            <v>STRING</v>
                            <v>POINTER TO SuctionPad</v>
                            <v>DINT</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>ENO</v>
                            <v>donePulse</v>
                            <v>done</v>
                            <v>busy</v>
                            <v>error</v>
                            <v>recovery</v>
                            <v>failCounter</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>INT</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <v n="EN">true</v>
                        <v n="ENO">true</v>
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">201L</v>
                      </o>
                      <o>
                        <v n="BoxType">"AOI_LoadFlatCardboard"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"aoiFlatCardboardRight"</v>
                          <v n="Type">"AOI_LoadFlatCardboard"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">198L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">111L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">112L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">113L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">114L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">115L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"INT"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">116L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">true</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"TRUE"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">118L</v>
                            </o>
                            <v n="Id">117L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">120L</v>
                            </o>
                            <v n="Id">119L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"sectionID"</v>
                              <v n="Type">"SectionEnum"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">122L</v>
                            </o>
                            <v n="Id">121L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"robotRight"</v>
                              <v n="Type">"RobotA22"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">124L</v>
                            </o>
                            <v n="Id">123L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"skidRight"</v>
                              <v n="Type">"SkidMagazine"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">126L</v>
                            </o>
                            <v n="Id">125L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"outerLoadedMaterials"</v>
                              <v n="Type">"ARRAY [Surface.TOP..Surface.BOTTOM_RIGHT] OF STRING"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">128L</v>
                            </o>
                            <v n="Id">127L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <v n="Type">"Surface"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">130L</v>
                            </o>
                            <v n="Id">129L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <v n="Type">"STRING"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">132L</v>
                            </o>
                            <v n="Id">131L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <v n="Type">"POINTER TO SuctionPad"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">134L</v>
                            </o>
                            <v n="Id">133L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <v n="Type">"DINT"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">136L</v>
                            </o>
                            <v n="Id">135L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>EN</v>
                            <v>execute</v>
                            <v>sectionID</v>
                            <v>robot</v>
                            <v>skid</v>
                            <v>loadedMaterials</v>
                            <v>surfaceID</v>
                            <v>material</v>
                            <v>suctions</v>
                            <v>numPads</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>SectionEnum[REF]</v>
                            <v>RobotA22[REF]</v>
                            <v>SkidMagazine[REF]</v>
                            <v>POINTER TO STRING</v>
                            <v>Surface</v>
                            <v>STRING</v>
                            <v>POINTER TO SuctionPad</v>
                            <v>DINT</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>ENO</v>
                            <v>donePulse</v>
                            <v>done</v>
                            <v>busy</v>
                            <v>error</v>
                            <v>recovery</v>
                            <v>failCounter</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>INT</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <v n="EN">true</v>
                        <v n="ENO">true</v>
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">199L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">1L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeBox">
                      <o>
                        <v n="BoxType">"PML_UnitModeManager"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"pmlModeManager"</v>
                          <v n="Type">"PML_UnitModeManager"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">236L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">"pmlMode"</v>
                              <v n="Type">"E_PMLProtectedUnitMode"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">238L</v>
                            </o>
                            <o>
                              <v n="Operand">"pmlModeString"</v>
                              <v n="Type">"STRING"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">239L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">240L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"UDINT"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">241L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"UDINT"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">242L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">true</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"TRUE"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">244L</v>
                            </o>
                            <v n="Id">243L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"NOT(pmlModeManager.bExecute)"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">246L</v>
                            </o>
                            <v n="Id">245L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"pmlModeRequest"</v>
                              <v n="Type">"E_PMLProtectedUnitMode"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">248L</v>
                            </o>
                            <v n="Id">247L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"pmlState"</v>
                              <v n="Type">"E_PMLState"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">250L</v>
                            </o>
                            <v n="Id">249L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>EN</v>
                            <v>bExecute</v>
                            <v>eModeCommand</v>
                            <v>eState</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>DINT</v>
                            <v>E_PMLState</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>ENO</v>
                            <v>eModeStatus</v>
                            <v>sModeStatus</v>
                            <v>bDone</v>
                            <v>bError</v>
                            <v>nErrorId</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>DINT</v>
                            <v>STRING</v>
                            <v>BOOL</v>
                            <v>BOOL</v>
                            <v>UDINT</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <v n="EN">true</v>
                        <v n="ENO">true</v>
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">237L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">235L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeBox">
                      <o>
                        <v n="BoxType">"PML_StateMachine"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"pmlStateMachine"</v>
                          <v n="Type">"PML_StateMachine"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">252L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">"pmlState"</v>
                              <v n="Type">"E_PMLState"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">254L</v>
                            </o>
                            <o>
                              <v n="Operand">"pmlStateString"</v>
                              <v n="Type">"STRING"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">255L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">256L</v>
                            </o>
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"UDINT"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">257L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">true</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"TRUE"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">259L</v>
                            </o>
                            <v n="Id">258L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"pmlMode"</v>
                              <v n="Type">"E_PMLProtectedUnitMode"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">261L</v>
                            </o>
                            <v n="Id">260L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"pmlCommand"</v>
                              <v n="Type">"E_PMLCommand"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">263L</v>
                            </o>
                            <v n="Id">262L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <v n="Type">"ST_PMLSubUnitInfoRef"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">265L</v>
                            </o>
                            <v n="Id">264L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">""</v>
                              <v n="Type">"ST_PMLStateMachineOptions"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">267L</v>
                            </o>
                            <v n="Id">266L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>EN</v>
                            <v>eMode</v>
                            <v>eCommand</v>
                            <v>stSubUnitInfoRef</v>
                            <v>stOptions</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>DINT</v>
                            <v>E_PMLCommand</v>
                            <v>ST_PMLSubUnitInfoRef</v>
                            <v>ST_PMLStateMachineOptions</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>ENO</v>
                            <v>eState</v>
                            <v>sState</v>
                            <v>bError</v>
                            <v>nErrorID</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>E_PMLState</v>
                            <v>STRING</v>
                            <v>BOOL</v>
                            <v>UDINT</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <v n="EN">true</v>
                        <v n="ENO">true</v>
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">253L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">251L</v>
                  </o>
                </l2>
                <v n="BranchCounter">0</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
              <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
              <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
              <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
              <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
              <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Action>
    <Action Name="callLocalModules" Id="{39933dae-94a6-4c04-af7d-ba6ce828a93a}" FolderPath="Actions\">
      <Implementation>
        <ST><![CDATA[{warning disable C0371}
insertionLeft(
	enable:= TRUE, 
	slider:= verticalDriveLeft, 
	screw:= horizontalDriveLeft, 
	contact=> , 
	softContact=> , 
	active=> , 
	error=> , 
	home=> , 
	homingComplete=> , 
	sliderPos=> );
	
insertionRight(
	enable:= TRUE, 
	slider:= verticalDriveRight, 
	screw:= horizontalDriveRight, 
	contact=> , 
	softContact=> , 
	active=> , 
	error=> , 
	home=> , 
	homingComplete=> , 
	sliderPos=> );]]></ST>
      </Implementation>
    </Action>
    <Action Name="configPML" Id="{e2ece0c0-9b34-41c9-bbf3-a047ef5004c6}" FolderPath="Actions\">
      <Implementation>
        <ST><![CDATA[pmlSemiAutoConfig(
	eMode:= 4, 
	sName:= 'SemiAuto', 
	bDisableClearing:= FALSE, 
	bDisableStarting:= FALSE, 
	bDisableSuspended:= FALSE, 
	bDisableStopping:= FALSE, 
	bDisableAborting:= FALSE, 
	bDisableHolding:= FALSE, 
	bDisableHeld:= FALSE, 
	bDisableUnholding:= FALSE, 
	bDisableSuspending:= FALSE, 
	bDisableUnsuspending:= FALSE, 
	bDisableResetting:= FALSE, 
	bDisableIdle:= FALSE, 
	bDisableCompleting:= FALSE, 
	bDisableComplete:= FALSE, 
	bEnableUnitModeChangeStopped:= TRUE, 
	bEnableUnitModeChangeIdle:= TRUE, 
	bEnableUnitModeChangeSuspended:= FALSE, 
	bEnableUnitModeChangeExecute:= FALSE, 
	bEnableUnitModeChangeAborted:= TRUE, 
	bEnableUnitModeChangeHeld:= FALSE, 
	bEnableUnitModeChangeComplete:= FALSE, 
	bError=> , 
	nErrorId=> );]]></ST>
      </Implementation>
    </Action>
    <Action Name="homingSequence" Id="{78b7d1d6-acc4-48dd-8084-f7fed3d74fa3}" FolderPath="Actions\">
      <Implementation>
        <ST><![CDATA[insertionLeft.homingSequence();
insertionRight.homingSequence();
pistonBottom.retract();]]></ST>
      </Implementation>
    </Action>
    <Method Name="load" Id="{a681c93d-e590-4020-9185-d7ae010cf638}">
      <Declaration><![CDATA[METHOD PROTECTED load : BOOL
VAR_INPUT
	pairIndex : INT;
END_VAR
VAR
	pair : REFERENCE TO PositionMaterials REF= materialsArr[pairIndex];
	nextPair : REFERENCE TO PositionMaterials;
END_VAR
(*
unlike other sections, the load() function for cardboard + corner guard only loads the corners
to load flat cardboards, use the function loadFlats()
*)]]></Declaration>
      <Implementation>
        <ST><![CDATA[{warning disable C0371}

IF robotLeft.error OR robotRight.error THEN
	RETURN;
ELSIF NOT (robotLeft.reserve(sectionID) AND robotRight.reserve(sectionID)) THEN //both robots must be reserved first
	RETURN;
END_IF

IF pairIndex + 1 < GVL.maxPairs THEN
	nextPair REF= materialsArr[pairIndex + 1];
END_IF

CASE masterLoadStep OF
	0: //load this pair's side cardboards
		masterLoadStep := 10;
		IF
			loadFlatCardboardsEx(
				robot:= robotLeft, 
				aoiLoad:= aoiFlatCardboardLeft, 
				loadStep:= loadStepLeft, 
				pairIndex:= pairIndex, 
				includeTop:= FALSE, 
				includeLeft:= TRUE, 
				includeRight:= FALSE, 
				includeBottom:= FALSE, 
				error=> )
			AND
			loadFlatCardboardsEx(
				robot:= robotLeft, 
				aoiLoad:= aoiFlatCardboardLeft, 
				loadStep:= loadStepLeft, 
				pairIndex:= pairIndex, 
				includeTop:= FALSE, 
				includeLeft:= FALSE, 
				includeRight:= TRUE, 
				includeBottom:= FALSE, 
				error=> )
		THEN
			masterLoadStep := 10;
			loadStepLeft := loadStepRight := 0;
		END_IF
		
		
	10: //next pair (which is to be placed over this pair) has the same position as this pair
		IF pairIndex + 1 >= GVL.maxPairs THEN //no next pair - final pair is index 15 (16-1), not 16
			masterLoadStep := 20;
			loadStepLeft := loadStepRight := 0;
			
		ELSIF pair.position < nextPair.position THEN
			masterLoadStep := 20;
			loadStepLeft := loadStepRight := 0;
		(*	
		ELSIF MatchesMaterialType(pair:= nextPair, materialType:= 'CAR') AND_THEN loadCornerCardboards(pairIndex:= pairIndex + 1) THEN
			masterLoadStep := 20;
			loadStepLeft := loadStepRight := 0;
		*)
		ELSIF MatchesMaterialType(pair:= nextPair, materialType:= 'COR') AND_THEN loadCornerGuards(pairIndex:= pairIndex + 1) THEN
			masterLoadStep := 20;
			loadStepLeft := loadStepRight := 0;
			
		END_IF
		
	20: //load current pair
		IF
			MatchesMaterialType(pair:= pair, materialType:= 'CAR') AND_THEN loadCornerCardboards(pairIndex:= iPair) OR_ELSE
			MatchesMaterialType(pair:= pair, materialType:= 'COR') AND_THEN loadCornerGuards(pairIndex:= iPair)
		THEN //is cardboard
			loadStepLeft := loadStepRight := 0;
			masterLoadStep := COMPLETE;
		END_IF
	
	COMPLETE:
		robotLeft.release(sectionID);
		robotRight.release(sectionID);
		
		loadStepLeft := loadStepRight := 0;
		masterLoadStep := 0;
		load := TRUE;
	
END_CASE]]></ST>
      </Implementation>
    </Method>
    <Method Name="loadCornerCardboards" Id="{fc6e26f1-7233-42c4-a94a-66d2e256266a}" FolderPath="Corner Cardboard\">
      <Declaration><![CDATA[METHOD PROTECTED loadCornerCardboards : BOOL
VAR_INPUT
	pairIndex : INT;
END_VAR
VAR_OUTPUT
	error : BOOL;
END_VAR
VAR
	errorLeft, errorRight : BOOL;
	leftSuctionArr, rightSuctionArr : POINTER TO SuctionPad;
	leftNextSet, rightNextSet : INT;
	leftMaterial, rightMaterial : STRING;
	leftFold, rightFold : INT;
	
	pair : REFERENCE TO PositionMaterials REF= materialsArr[pairIndex];
	topLeftFold : INT := topLeftFoldsArr[pairIndex];
	topRightFold : INT := topRightFoldsArr[pairIndex];
	bottomLeftFold : INT := bottomLeftFoldsArr[pairIndex];
	bottomRightFold : INT := bottomRightFoldsArr[pairIndex];
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[{warning disable C0371}

loadCornerCardboards := 
	loadCornerCardboardsEx(
		robot:= robotLeft, 
		aoiLoad:= aoiCornerCardboardLeft, 
		loadStep:= loadStepLeft, 
		pairIndex:= pairIndex, 
		includeTopLeft:= TRUE, 
		includeTopRight:= FALSE, 
		includeBottomLeft:= TRUE, 
		includeBottomRight:= FALSE, 
		error=> errorLeft)
	AND
	loadCornerCardboardsEx(
		robot:= robotRight, 
		aoiLoad:= aoiCornerCardboardRight, 
		loadStep:= loadStepRight, 
		pairIndex:= pairIndex, 
		includeTopLeft:= FALSE, 
		includeTopRight:= TRUE, 
		includeBottomLeft:= FALSE, 
		includeBottomRight:= TRUE, 
		error=> errorLeft);
		
error := errorLeft OR errorRight;

(*
CASE cornerSetLeft OF
	0:
		leftNextSet := Surface.TOP_RIGHT;
		cornerSetLeft := 0;
		
	Surface.TOP_RIGHT: 
		leftNextSet := Surface.TOP_LEFT;
		leftSuctionArr := suctionTopRight;
		leftMaterial := pair.topRight;
		leftFold := topRightFold;
		
	Surface.TOP_LEFT: 
		leftNextSet := Surface.BOTTOM_RIGHT;
		leftSuctionArr := suctionTopLeft;
		leftMaterial := pair.topLeft;
		leftFold := topLeftFold;
		
	Surface.BOTTOM_RIGHT:
		leftNextSet := Surface.BOTTOM_LEFT;
		leftSuctionArr := suctionBottomRight;
		leftMaterial := pair.bottomRight;
		leftFold := bottomRightFold;
		
	Surface.BOTTOM_LEFT: 
		leftNextSet := COMPLETE;
		leftSuctionArr := suctionBottomLeft;
		leftMaterial := pair.bottomLeft;
		leftFold := bottomLeftFold;
END_CASE
IF
	(cornerSetLeft = 0 OR cornerSetLeft = COMPLETE) OR_ELSE
	leftCornerSequence(
		robot:= robotLeft, 
		skid:= skidLeft, 
		suctions := leftSuctionArr,
		loadStep:= loadStepLeft, 
		surfaceID:= cornerSetLeft,
		material:= pair.topRight, 
		foldPos0:= topRightFold, 
		foldPos1:= 0, 
		error=> )
THEN
	cornerSetLeft := leftNextSet;
	loadStepLeft := 0;
END_IF


CASE cornerSetRight OF
	0:
		cornerSetRight := Surface.TOP_RIGHT;
		rightSuctionArr := suctionTopRight;
		
	Surface.TOP_RIGHT:		
		rightNextSet := Surface.BOTTOM_RIGHT;
		rightSuctionArr := suctionTopRight;
		rightMaterial := pair.topRight;
		rightFold := topRightFold;
		
	Surface.BOTTOM_RIGHT: 
		rightNextSet := COMPLETE;
		rightSuctionArr := suctionBottomRight;
		rightMaterial := pair.bottomRight;
		rightFold := bottomRightFold;		
END_CASE
IF
	(cornerSetRight = 0 OR cornerSetRight = COMPLETE) OR_ELSE
	rightCornerSequence(
		robot:= robotRight, 
		skid:= skidRight, 
		suctions := rightSuctionArr,
		loadStep:= loadStepRight, 
		material:= pair.topRight, 
		surfaceID:= cornerSetRight,
		foldPos0:= pair.topRightFold, 
		foldPos1:= 0, 
		error=> )
THEN
	cornerSetRight := rightNextSet;
	loadStepRight := 0;
END_IF



IF cornerSetLeft = COMPLETE AND cornerSetRight = COMPLETE THEN
	loadCornerCardboards := TRUE;
	
	loadStepLeft := loadStepRight := 0;
	cornerSetLeft := cornerSetRight := 0;
END_IF
*)]]></ST>
      </Implementation>
    </Method>
    <Method Name="loadCornerCardboardsEx" Id="{156f628d-7b56-4840-9717-9971eeb42365}" FolderPath="Corner Cardboard\">
      <Declaration><![CDATA[METHOD PROTECTED loadCornerCardboardsEx : BOOL
VAR_IN_OUT
	robot : RobotA22;
	aoiLoad : AOI_LoadCornerCardboard;
	loadStep : INT;
END_VAR
VAR_INPUT
	pairIndex : INT;
	includeTopLeft, includeTopRight, includeBottomLeft, includeBottomRight : BOOL;
END_VAR
VAR_OUTPUT
	error : BOOL;
END_VAR
VAR
	suctionsArrLeft, suctionsArrRight : POINTER TO SuctionPad;
	nextSetLeft, nextSetRight : INT;

	pair : REFERENCE TO PositionMaterials REF= materialsArr[pairIndex];
	topLeftFold : INT := topLeftFoldsArr[pairIndex];
	topRightFold : INT := topRightFoldsArr[pairIndex];
	bottomLeftFold : INT := bottomLeftFoldsArr[pairIndex];
	bottomRightFold : INT := bottomRightFoldsArr[pairIndex];
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[{warning disable C0371}

IF robot.error THEN
	error := TRUE;
	RETURN;
ELSIF robot.reservation <> sectionID AND_THEN NOT robot.reserve(sectionID) THEN
	RETURN;
ELSIF robot.tool <> sectionID AND_THEN NOT robot.changeEOAT(targetTool := sectionID) THEN
	RETURN;
END_IF

error := aoiLoad.error;

CASE loadStep OF
	0:
		loadStep := Surface.BOTTOM_LEFT;
		
	Surface.BOTTOM_LEFT:
		IF NOT includeBottomLeft OR aoiLoad.donePulse THEN
			aoiLoad.execute := FALSE;
			aoiLoad.material := '';
			loadStep := Surface.BOTTOM_RIGHT;
			RETURN;
		END_IF
		
		aoiLoad.surfaceID := loadStep;
		aoiLoad.material := pair.bottomLeft;
		aoiLoad.suctions := suctionBottomLeft;
		aoiLoad.numPads := UPPER_BOUND(suctionBottomLeft, 1) - LOWER_BOUND(suctionBottomLeft, 1) + 1;
		
		aoiLoad.foldPos0 := bottomLeftFold;
		aoiLoad.foldPos1 := 0;
		
		aoiLoad.execute := NOT aoiLoad.busy;
		
	Surface.BOTTOM_RIGHT:
		IF NOT includeBottomRight OR aoiLoad.donePulse THEN
			aoiLoad.execute := FALSE;
			aoiLoad.material := '';
			loadStep := Surface.TOP_LEFT;
			RETURN;
		END_IF
		
		aoiLoad.surfaceID := loadStep;
		aoiLoad.material := pair.bottomRight;
		aoiLoad.suctions := suctionBottomRight;
		aoiLoad.numPads := UPPER_BOUND(suctionBottomRight, 1) - LOWER_BOUND(suctionBottomRight, 1) + 1;
		
		aoiLoad.foldPos0 := bottomRightFold;
		aoiLoad.foldPos1 := 0;
		
		aoiLoad.execute := NOT aoiLoad.busy;
	
	Surface.TOP_LEFT:		
		IF NOT includeTopLeft OR aoiLoad.donePulse THEN
			aoiLoad.execute := FALSE;
			aoiLoad.material := '';
			loadStep := Surface.TOP_RIGHT;
			RETURN;
		END_IF
		
		aoiLoad.surfaceID := loadStep;
		aoiLoad.material := pair.top;
		aoiLoad.suctions := suctionTopLeft;
		aoiLoad.numPads := UPPER_BOUND(suctionTopLeft, 1) - LOWER_BOUND(suctionTopLeft, 1) + 1;
		
		aoiLoad.foldPos0 := topLeftFold;
		aoiLoad.foldPos1 := 0;
		
		aoiLoad.execute := NOT aoiLoad.busy;
		
	Surface.TOP_RIGHT:
		IF NOT includeTopRight OR aoiLoad.donePulse THEN
			aoiLoad.execute := FALSE;
			aoiLoad.material := '';
			loadStep := COMPLETE;
			RETURN;
		END_IF
		
		aoiLoad.surfaceID := loadStep;
		aoiLoad.material := pair.topRight;
		aoiLoad.suctions := suctionTopRight;
		aoiLoad.numPads := UPPER_BOUND(suctionTopRight, 1) - LOWER_BOUND(suctionTopRight, 1) + 1;
		
		aoiLoad.foldPos0 := topRightFold;
		aoiLoad.foldPos1 := 0;
		
		aoiLoad.execute := NOT aoiLoad.busy;
		
	COMPLETE:				
		robot.release(sectionID);
		
		aoiLoad.material := '';
		aoiLoad.execute := FALSE;
		
		loadCornerCardboardsEx := TRUE;
END_CASE]]></ST>
      </Implementation>
    </Method>
    <Method Name="loadCornerGuards" Id="{f8d7145e-2601-4096-b20d-bfa97c3f5492}" FolderPath="Corner Guards\">
      <Declaration><![CDATA[METHOD loadCornerGuards : BOOL
VAR_INPUT
	pairIndex : INT;
END_VAR
VAR_OUTPUT
	error : BOOL;
END_VAR
VAR
	pair : REFERENCE TO PositionMaterials REF= materialsArr[pairIndex];
	errorLeft, errorRight : BOOL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[{warning disable C0371}

loadCornerGuards := 
	loadCornerGuardsEx(
		robot:= robotLeft, 
		aoiLoad:= aoiCornerGuardLeft, 
		loadStep:= loadStepLeft, 
		pairIndex:= pairIndex, 
		includeTopLeft:= TRUE, 
		includeTopRight:= FALSE, 
		includeBottomLeft:= TRUE, 
		includeBottomRight:= FALSE, 
		error=> errorLeft) 
	AND
	loadCornerGuardsEx(
		robot:= robotRight, 
		aoiLoad:= aoiCornerGuardRight, 
		loadStep:= loadStepRight, 
		pairIndex:= pairIndex, 
		includeTopLeft:= FALSE, 
		includeTopRight:= TRUE, 
		includeBottomLeft:= FALSE, 
		includeBottomRight:= TRUE, 
		error=> errorRight);
		
error := errorLeft OR errorRight;

(*
IF robotLeft.error OR robotRight.error THEN
	error := TRUE;
	RETURN;
	
ELSIF 
	(robotLeft.reservation <> sectionID AND_THEN NOT robotLeft.reserve(sectionID)) OR 
	(robotRight.reservation <> sectionID AND_THEN NOT robotRight.reserve(sectionID))
THEN //loading requires both robots be reserved together
	RETURN;
	
ELSIF //robots have wrong tool
	(robotLeft.tool <> sectionID AND_THEN NOT robotLeft.changeEOAT(targetTool := sectionID)) OR
	(robotRight.tool <> sectionID AND_THEN NOT robotRight.changeEOAT(targetTool := sectionID))
THEN
	RETURN;
	
END_IF

CASE loadStep OF
	0: //top and bottom
		IF aoiCornerGuardLeft.done AND aoiCornerGuardRight.done THEN
			aoiCornerGuardLeft.execute := aoiCornerGuardRight.execute := FALSE;
			aoiCornerGuardLeft.material := aoiCornerGuardRight.material := '';
			loadStep := 10;
			RETURN;
		END_IF
		
		aoiCornerGuardLeft.suctions := 0;
		aoiCornerGuardLeft.surfaceID := Surface.TOP;
		aoiCornerGuardLeft.material := pair.top;
		aoiCornerGuardLeft.numPads := 0;
		
		aoiCornerGuardRight.suctions := suctionBottom;
		aoiCornerGuardRight.surfaceID := Surface.BOTTOM;
		aoiCornerGuardRight.material := pair.bottom;
		aoiCornerGuardRight.numPads := 0;
		
		aoiCornerGuardLeft.execute := NOT aoiCornerGuardLeft.done AND NOT aoiCornerGuardLeft.busy;
		aoiCornerGuardRight.execute := NOT aoiCornerGuardRight.done AND NOT aoiCornerGuardRight.busy;
		
	10: //sides
		IF aoiCornerGuardLeft.done AND aoiCornerGuardRight.done THEN
			aoiCornerGuardLeft.execute := aoiCornerGuardRight.execute := FALSE;
			aoiCornerGuardLeft.material := aoiCornerGuardRight.material := '';
			loadStep := 10;
			RETURN;
		END_IF
		
		aoiCornerGuardLeft.suctions := 0;
		aoiCornerGuardLeft.surfaceID := Surface.LEFT;
		aoiCornerGuardLeft.material := pair.left;
		aoiCornerGuardLeft.numPads := 0;
		
		aoiCornerGuardRight.suctions := 0;
		aoiCornerGuardRight.surfaceID := Surface.RIGHT;
		aoiCornerGuardRight.material := pair.right;
		aoiCornerGuardRight.numPads := 0;
		
		aoiCornerGuardLeft.execute := NOT aoiCornerGuardLeft.done AND NOT aoiCornerGuardLeft.busy;
		aoiCornerGuardRight.execute := NOT aoiCornerGuardRight.done AND NOT aoiCornerGuardRight.busy;
		
	COMPLETE:
		loadStep := 0;
		loadCornerGuards := TRUE;
END_CASE

error := aoiCornerGuardLeft.error OR aoiCornerGuardRight.error;
*)]]></ST>
      </Implementation>
    </Method>
    <Method Name="loadCornerGuardsEx" Id="{ac43d9ca-0f0f-4142-b559-dd30cf7e65a4}" FolderPath="Corner Guards\">
      <Declaration><![CDATA[METHOD loadCornerGuardsEx : BOOL
VAR_IN_OUT
	robot : RobotA22;
	aoiLoad : AOI_LoadCornerGuard;
	loadStep : INT;
END_VAR
VAR_INPUT
	pairIndex : INT;
	includeTopLeft, includeTopRight, includeBottomLeft, includeBottomRight : BOOL;
END_VAR
VAR_OUTPUT
	error : BOOL;
END_VAR
VAR
	pair : REFERENCE TO PositionMaterials REF= materialsArr[pairIndex];
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[{warning disable C0371}
IF robot.error THEN
	error := TRUE;
	RETURN;
ELSIF robot.reservation <> sectionID AND_THEN NOT robot.reserve(sectionID) THEN
	RETURN;
ELSIF robot.tool <> sectionID AND_THEN NOT robot.changeEOAT(targetTool := sectionID) THEN
	RETURN;
END_IF

error := aoiLoad.error;

CASE loadStep OF
	0:
		loadStep := Surface.BOTTOM_LEFT;
		
	Surface.BOTTOM_LEFT:
		IF NOT includeBottomLeft OR aoiLoad.donePulse THEN
			aoiLoad.execute := FALSE;
			aoiLoad.material := '';
			loadStep := Surface.BOTTOM_RIGHT;
			RETURN;
		END_IF
		
		aoiLoad.surfaceID := loadStep;
		aoiLoad.material := pair.bottomLeft;
		aoiLoad.suctions := suctionBottomLeft;
		aoiLoad.numPads := UPPER_BOUND(suctionBottomLeft, 1) - LOWER_BOUND(suctionBottomLeft, 1) + 1;
		
		aoiLoad.execute := NOT aoiLoad.busy;
		
	Surface.BOTTOM_RIGHT:
		IF NOT includeBottomRight OR aoiLoad.donePulse THEN
			aoiLoad.execute := FALSE;
			aoiLoad.material := '';
			loadStep := Surface.TOP_LEFT;
			RETURN;
		END_IF
		
		aoiLoad.surfaceID := loadStep;
		aoiLoad.material := pair.bottomRight;
		aoiLoad.suctions := suctionBottomRight;
		aoiLoad.numPads := UPPER_BOUND(suctionBottomRight, 1) - LOWER_BOUND(suctionBottomRight, 1) + 1;
		
		aoiLoad.execute := NOT aoiLoad.busy;
	
	Surface.TOP_LEFT:		
		IF NOT includeTopLeft OR aoiLoad.donePulse THEN
			aoiLoad.execute := FALSE;
			aoiLoad.material := '';
			loadStep := Surface.TOP_RIGHT;
			RETURN;
		END_IF
		
		aoiLoad.surfaceID := loadStep;
		aoiLoad.material := pair.top;
		aoiLoad.suctions := suctionTopLeft;
		aoiLoad.numPads := UPPER_BOUND(suctionTopLeft, 1) - LOWER_BOUND(suctionTopLeft, 1) + 1;
		
		aoiLoad.execute := NOT aoiLoad.busy;
		
	Surface.TOP_RIGHT:
		IF NOT includeTopRight OR aoiLoad.donePulse THEN
			aoiLoad.execute := FALSE;
			aoiLoad.material := '';
			loadStep := COMPLETE;
			RETURN;
		END_IF
		
		aoiLoad.surfaceID := loadStep;
		aoiLoad.material := pair.topRight;
		aoiLoad.suctions := suctionTopRight;
		aoiLoad.numPads := UPPER_BOUND(suctionTopRight, 1) - LOWER_BOUND(suctionTopRight, 1) + 1;
		
		aoiLoad.execute := NOT aoiLoad.busy;
		
	COMPLETE:				
		robot.release(sectionID);
		
		aoiLoad.material := '';
		aoiLoad.execute := FALSE;
		
		loadCornerGuardsEx := TRUE;
END_CASE]]></ST>
      </Implementation>
    </Method>
    <Method Name="loadFlatCardboards" Id="{b9a93d4c-938b-4af6-a5a3-5141d50c48d4}" FolderPath="Flat Cardboard\">
      <Declaration><![CDATA[METHOD PROTECTED loadFlatCardboards : BOOL
VAR_INPUT
	pairIndex : INT;
END_VAR
VAR_OUTPUT
	error : BOOL;
END_VAR
VAR
	pair : REFERENCE TO PositionMaterials REF= materialsArr[pairIndex];
	errorLeft, errorRight : BOOL;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[{warning disable C0371}

loadFlatCardboards := 
	loadFlatCardboardsEx(
		robot:= robotLeft, 
		aoiLoad:= aoiFlatCardboardLeft, 
		loadStep:= loadStepLeft, 
		pairIndex:= pairIndex, 
		includeTop:= TRUE, 
		includeLeft:= FALSE, //left already loaded before
		includeRight:= FALSE, 
		includeBottom:= FALSE, 
		error=> errorLeft)
	AND
	loadFlatCardboardsEx(
		robot:= robotRight, 
		aoiLoad:= aoiFlatCardboardRight, 
		loadStep:= loadStepRight, 
		pairIndex:= pairIndex, 
		includeTop:= FALSE, 
		includeLeft:= FALSE, 
		includeRight:= FALSE, //right already loaded before
		includeBottom:= TRUE, 
		error=> errorRight);
		
error := errorLeft OR errorRight;

(*
IF robotLeft.error OR robotRight.error THEN
	error := TRUE;
	RETURN;
	
ELSIF 
	(robotLeft.reservation <> sectionID AND_THEN NOT robotLeft.reserve(sectionID)) OR 
	(robotRight.reservation <> sectionID AND_THEN NOT robotRight.reserve(sectionID))
THEN //loading requires both robots be reserved together
	RETURN;
	
ELSIF //robots have wrong tool
	(robotLeft.tool <> sectionID AND_THEN NOT robotLeft.changeEOAT(targetTool := sectionID)) OR
	(robotRight.tool <> sectionID AND_THEN NOT robotRight.changeEOAT(targetTool := sectionID))
THEN
	RETURN;
	
END_IF

CASE loadStep OF
	0: //top and bottom
		IF aoiFlatCardboardLeft.done AND aoiFlatCardboardRight.done THEN
			aoiFlatCardboardLeft.execute := aoiFlatCardboardRight.execute := FALSE;
			aoiFlatCardboardLeft.material := aoiFlatCardboardRight.material := '';
			loadStep := 10;
			RETURN;
		END_IF
		
		aoiFlatCardboardLeft.suctions := 0;
		aoiFlatCardboardLeft.surfaceID := Surface.TOP;
		aoiFlatCardboardLeft.material := pair.top;
		aoiFlatCardboardLeft.numPads := 0;
		
		aoiFlatCardboardRight.suctions := suctionBottom;
		aoiFlatCardboardRight.surfaceID := Surface.BOTTOM;
		aoiFlatCardboardRight.material := pair.bottom;
		aoiFlatCardboardRight.numPads := 0;
		
		aoiFlatCardboardLeft.execute := NOT aoiFlatCardboardLeft.done AND NOT aoiFlatCardboardLeft.busy;
		aoiFlatCardboardRight.execute := NOT aoiFlatCardboardRight.done AND NOT aoiFlatCardboardRight.busy;
		
	10: //sides
		IF aoiFlatCardboardLeft.done AND aoiFlatCardboardRight.done THEN
			aoiFlatCardboardLeft.execute := aoiFlatCardboardRight.execute := FALSE;
			aoiFlatCardboardLeft.material := aoiFlatCardboardRight.material := '';
			loadStep := 10;
			RETURN;
		END_IF
		
		aoiFlatCardboardLeft.suctions := 0;
		aoiFlatCardboardLeft.surfaceID := Surface.LEFT;
		aoiFlatCardboardLeft.material := pair.left;
		aoiFlatCardboardLeft.numPads := 0;
		
		aoiFlatCardboardRight.suctions := 0;
		aoiFlatCardboardRight.surfaceID := Surface.RIGHT;
		aoiFlatCardboardRight.material := pair.right;
		aoiFlatCardboardRight.numPads := 0;
		
		aoiFlatCardboardLeft.execute := NOT aoiFlatCardboardLeft.done AND NOT aoiFlatCardboardLeft.busy;
		aoiFlatCardboardRight.execute := NOT aoiFlatCardboardRight.done AND NOT aoiFlatCardboardRight.busy;
		
	COMPLETE:
		loadStepLeft := loadStepRight := 0;
		loadStep := 0;
		
		loadFlatCardboards := TRUE;
END_CASE

error := aoiFlatCardboardLeft.error OR aoiFlatCardboardRight.error;
*)]]></ST>
      </Implementation>
    </Method>
    <Method Name="loadFlatCardboardsEx" Id="{26e40d6d-60a4-4c2c-bba4-a7493624a410}" FolderPath="Flat Cardboard\">
      <Declaration><![CDATA[METHOD loadFlatCardboardsEx : BOOL
VAR_IN_OUT
	robot : RobotA22;
	aoiLoad : AOI_LoadFlatCardboard;
	loadStep : INT;
END_VAR
VAR_INPUT
	pairIndex : INT;
	includeTop, includeLeft, includeRight, includeBottom : BOOL;
END_VAR
VAR_OUTPUT
	error : BOOL;
END_VAR
VAR
	pair : REFERENCE TO PositionMaterials REF= materialsArr[pairIndex];
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF robot.error THEN
	error := TRUE;
	RETURN;
ELSIF robot.reservation <> sectionID AND_THEN NOT robot.reserve(sectionID) THEN
	RETURN;
ELSIF robot.tool <> sectionID AND_THEN NOT robot.changeEOAT(targetTool := sectionID) THEN
	RETURN;
END_IF

error := aoiLoad.error;

CASE loadStep OF
	0:
		loadStep := Surface.TOP;
	
	Surface.TOP:	
		IF NOT includeTop OR aoiLoad.donePulse THEN
			aoiLoad.execute := FALSE;
			aoiLoad.material := '';
			loadStep := Surface.BOTTOM;
			RETURN;
		END_IF
		
		aoiLoad.surfaceID := Surface.TOP;
		aoiLoad.material := pair.top;
		aoiLoad.suctions := 0;
		aoiLoad.numPads := 0;
		
		aoiLoad.execute := NOT aoiLoad.busy;
		
	Surface.BOTTOM:
		IF NOT includeBottom OR aoiLoad.donePulse THEN
			aoiLoad.execute := FALSE;
			aoiLoad.material := '';
			loadStep := Surface.LEFT;
			RETURN;
		END_IF
		
		aoiLoad.surfaceID := Surface.BOTTOM;
		aoiLoad.material := pair.bottom;
		aoiLoad.suctions := suctionBottom;
		aoiLoad.numPads := UPPER_BOUND(suctionBottom, 1) - LOWER_BOUND(suctionBottom, 1) + 1;
		
		aoiLoad.execute := NOT aoiLoad.busy;
		
	Surface.LEFT:
		IF NOT includeLeft OR aoiLoad.donePulse THEN
			aoiLoad.execute := FALSE;
			aoiLoad.material := '';
			loadStep := Surface.RIGHT;
			RETURN;
		END_IF
		
		aoiLoad.surfaceID := Surface.LEFT;
		aoiLoad.material := pair.left;
		aoiLoad.suctions := 0;
		aoiLoad.numPads := 0;
		
		aoiLoad.execute := NOT aoiLoad.busy;
		
	Surface.RIGHT:
		IF NOT includeRight OR aoiLoad.donePulse THEN
			aoiLoad.execute := FALSE;
			aoiLoad.material := '';
			loadStep := COMPLETE;
			RETURN;
		END_IF
		
		aoiLoad.surfaceID := Surface.RIGHT;
		aoiLoad.material := pair.right;
		aoiLoad.suctions := 0;
		aoiLoad.numPads := 0;
		
		aoiLoad.execute := NOT aoiLoad.busy;
		
	COMPLETE:				
		robot.release(sectionID);
		
		aoiLoad.material := '';
		aoiLoad.execute := FALSE;
		
		loadFlatCardboardsEx := TRUE;
END_CASE]]></ST>
      </Implementation>
    </Method>
    <Method Name="maintenance" Id="{8dc492fc-7c74-48c6-a0e8-0f621ee44eb4}">
      <Declaration><![CDATA[METHOD PROTECTED maintenance : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[{warning disable C0371}
IF robotLeft.Done THEN
	robotLeft.clearCommand();
END_IF

IF robotRight.Done THEN
	robotRight.clearCommand();
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="process" Id="{12873255-c3e6-4f5b-bcd2-07be3d909921}">
      <Declaration><![CDATA[METHOD PROTECTED process : BOOL
VAR_INPUT
	auto : BOOL;
END_VAR
VAR_OUTPUT
	error : BOOL;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[{warning disable C0371}
(*
corrected sequence:
	load sides
	load corners
	load bottom
	load top
*)

CASE step OF
	IDLE:
		IF execute THEN
			execute := FALSE;
			step := LOAD_CORNERS;
		END_IF
	
	LOAD_CORNERS:
		IF
			(auto AND done) OR
			(NOT auto AND execute)
		THEN
			aoiCornerCardboardLeft.reset();
			aoiCornerCardboardRight.reset();
			
			aoiCornerGuardLeft.reset();
			aoiCornerGuardRight.reset();
			
			aoiFlatCardboardLeft.reset();
			aoiFlatCardboardRight.reset();
			
			step := LOAD_FLATS;
			RETURN;
		END_IF
		
		IF NOT done THEN
			done := load(pairIndex := iPair);
		END_IF
		
	LOAD_FLATS:
		IF
			(auto AND done) OR
			(NOT auto AND execute)
		THEN
			aoiCornerCardboardLeft.reset();
			aoiCornerCardboardRight.reset();
			
			aoiCornerGuardLeft.reset();
			aoiCornerGuardRight.reset();
			
			aoiFlatCardboardLeft.reset();
			aoiFlatCardboardRight.reset();
			
			step := PUSH;
			RETURN;
		END_IF
		
		IF NOT done THEN
			done := loadFlatCardboards(pairIndex := iPair);
		END_IF
		
	PUSH:
		IF
			(auto AND latchLeft AND latchRight AND pistonBottom.extended) OR
			(insertionLeft.contact AND insertionRight.contact AND pistonBottom.extended) OR
			(NOT auto AND execute)
		THEN
			step := TARGET_WRAP_POSITION;
			RETURN;
		END_IF
		
		IF //align slider to 5mm gap above bundle height
			NOT insertionLeft.align(1000-demoHeight+5) OR
			NOT insertionRight.align(1000-demoHeight+5)
		THEN
			RETURN;
		END_IF
		
		insertionLeft.press();
		insertionRight.press();
		pistonBottom.extend();
		
	TARGET_WRAP_POSITION:		
		IF iWrap >= wrapPoints THEN
			step := COMPLETE;
			RETURN;
		END_IF
		
		//loadNextPair := materialsArr[iPair].position = materialsArr[iPair + 1].position;	
		
		IF materialsArr[iPair].position = materialsArr[iPair + 1].position THEN
			masterLength := MAX( GetPairMasterLength(materialsArr[iPair]), GetPairMasterLength(materialsArr[iPair + 1]) );
			wrapPoints := MAX( materialsArr[iPair].wrapPoints, materialsArr[iPair + 1].wrapPoints );
			wrapRotations := MAX( materialsArr[iPair].wrapRotations, materialsArr[iPair + 1].wrapRotations );
		ELSE
			masterLength := GetPairMasterLength(materialsArr[iPair]);
			wrapPoints := materialsArr[iPair].wrapPoints;
			wrapRotations := materialsArr[iPair].wrapRotations;
		END_IF
		
		(*
		directionCheckAndSet(
			wrapConveyorPos,
			(currentPair.position - masterLength/2) + (masterLength/(currentPair.wrapPoints + 1) * (iWrap + 1)));
		*)
		step := WRAP_AND_RELEASE;
		
	WRAP_AND_RELEASE:
		releaseDelayTimer(IN:= , PT:= releaseDelay, Q=> , ET=> );
		
		IF wrapper.ready THEN
			wrapper.wrap(wrapRotations);
			releaseDelayTimer.IN := TRUE;
		END_IF
		
		IF releaseDelayTimer.Q THEN
			SetSuctions(suctions := suctionTopLeft, state := FALSE);
			SetSuctions(suctions := suctionTopRight, state := FALSE);
			SetSuctions(suctions := suctionBottomLeft, state := FALSE);
			SetSuctions(suctions := suctionBottomRight, state := FALSE);
			
			insertionLeft.align(0);
			insertionRight.align(0);
			insertionLeft.release();
			insertionRight.release();
			
			pistonBottom.retract();
		END_IF
		
		IF wrapper.done AND insertionLeft.home AND insertionRight.home AND pistonBottom.retracted THEN
			releaseDelayTimer.IN := FALSE;
			step := WRAP_AND_RELEASE;
		END_IF
	
	COMPLETE:
		iPair := (iPair + 1) MOD GVL.maxPairs;
		iWrap := wrapPoints := wrapRotations := 0;
		step := IDLE;
		
END_CASE]]></ST>
      </Implementation>
    </Method>
    <Method Name="ps_Aborting" Id="{d369707c-28f8-4c64-966f-5bb6a3587ba5}" FolderPath="PML Inter. States\">
      <Declaration><![CDATA[METHOD PRIVATE ps_Aborting : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[{warning disable C0371}
insertionLeft.stop();
insertionRight.stop();
pistonBottom.stop();

aoiFlatCardboardLeft.reset();
aoiFlatCardboardRight.reset();

aoiCornerCardboardLeft.reset();
aoiCornerCardboardRight.reset();

aoiCornerGuardLeft.reset();
aoiCornerGuardRight.reset();

robotLeft.clearCommand();
robotRight.clearCommand();

//stop conveyors

ps_Aborting :=
	NOT insertionLeft.active AND
	NOT insertionRight.active AND
	NOT pistonBottom.busy AND
	NOT robotLeft.Busy AND
	NOT robotRight.Busy;]]></ST>
      </Implementation>
    </Method>
    <Method Name="ps_Clearing" Id="{b1bcfdaf-5358-4ace-937d-293bb0c837c2}" FolderPath="PML Inter. States\">
      <Declaration><![CDATA[METHOD PRIVATE ps_Clearing : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[{warning disable C0371}
insertionLeft.reset();
insertionRight.reset();

ps_Clearing := 
	NOT insertionLeft.error AND
	NOT insertionRight.error AND
	NOT wrapper.error AND
	NOT robotLeft.error AND
	NOT robotRight.error;]]></ST>
      </Implementation>
    </Method>
    <Method Name="ps_Execute" Id="{13d5106d-1f4d-4d49-93f3-7e4ba04d0dc5}" FolderPath="PML Inter. States\">
      <Declaration><![CDATA[METHOD PRIVATE ps_Execute : BOOL
VAR_INPUT
END_VAR
VAR_OUTPUT
	error : BOOL;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[CASE pmlMode OF
	0: //invalid mode
	ePMLProtUnitMode_Production:	ps_Execute := process(auto := TRUE, error => error);
	ePMLProtUnitMode_Maintenance:	maintenance();
	ePMLProtUnitMode_Manual:		maintenance(); //same as maintenance for now
	4 (*SemiAuto*):					ps_Execute := process(auto := FALSE, error => error);
END_CASE]]></ST>
      </Implementation>
    </Method>
    <Method Name="ps_Holding" Id="{9c0c96db-5709-4873-af32-26d4591962e1}" FolderPath="PML Inter. States\">
      <Declaration><![CDATA[METHOD PRIVATE ps_Holding : BOOL
VAR_INPUT
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[{warning disable C0371}
insertionLeft.stop();
insertionRight.stop();
pistonBottom.stop();
//set robot to pause

ps_Holding :=
	NOT insertionLeft.active AND
	NOT insertionRight.active;]]></ST>
      </Implementation>
    </Method>
    <Method Name="ps_Resetting" Id="{ed7fb93f-1f68-484d-bf76-f2c9f1db3c72}" FolderPath="PML Inter. States\">
      <Declaration><![CDATA[METHOD PRIVATE ps_Resetting : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[{warning disable C0371}
insertionLeft.reset();
insertionRight.reset();

ps_Resetting := 
	reset AND
	NOT insertionLeft.error AND
	NOT insertionRight.error AND
	NOT wrapper.error AND
	NOT robotLeft.error AND
	NOT robotRight.error;]]></ST>
      </Implementation>
    </Method>
    <Method Name="ps_Starting" Id="{7764a973-763c-4f51-8655-e151dbd80f89}" FolderPath="PML Inter. States\">
      <Declaration><![CDATA[METHOD PRIVATE ps_Starting : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[{warning disable C0371}
robotLeft.clearCommand();
robotRight.clearCommand();

insertionLeft.homingSequence();
insertionRight.homingSequence();
pistonBottom.retract();

ps_Starting := 
	insertionLeft.screw.HomeSet AND 
	insertionRight.screw.HomeSet AND 
	pistonBottom.retracted;]]></ST>
      </Implementation>
    </Method>
    <Method Name="ps_Stopping" Id="{194f87af-0f78-4bc2-825a-74091d7c1f8d}" FolderPath="PML Inter. States\">
      <Declaration><![CDATA[METHOD PRIVATE ps_Stopping : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[{warning disable C0371}
insertionLeft.stop();
insertionRight.stop();
pistonBottom.stop();

aoiFlatCardboardLeft.reset();
aoiFlatCardboardRight.reset();

aoiCornerCardboardLeft.reset();
aoiCornerCardboardRight.reset();

aoiCornerGuardLeft.reset();
aoiCornerGuardRight.reset();

robotLeft.clearCommand();
robotRight.clearCommand();

wrapper.bEnable := FALSE;

//stop conveyors

ps_Stopping :=
	//NOT insertionLeft.active AND
	NOT insertionRight.active AND
	NOT pistonBottom.busy AND
	NOT robotLeft.Busy AND
	NOT robotRight.Busy AND
	NOT wrapper.busy;]]></ST>
      </Implementation>
    </Method>
    <Action Name="runPML" Id="{d7b0eaa1-6020-4821-b965-4387abf70c30}" FolderPath="Actions\">
      <Implementation>
        <ST><![CDATA[(*
PackML
	state machine for packaging applications - see Tc3_PackML_V2 library on InfoSys
	
	final states - wait for an input or condition and command to new state
	intermediate states - complete a task and call pmlStateMachine.M_StateComplete() to advance to next state
	
the following states currently use the same logic (albeit in different methods), implementation may change later
	ps_Stopping() and ps_Aborting()
	ps_Resetting() and ps_Clearing()
	
STOP - controlled stop **with intent to shutdown or vacate for extended time** induced by operator/HMI - otherwise use HOLD
ABORT - emergency stop due to machine errors


HOLD - minor local issues
SUSPEND - external issues

EXECUTE - major control logic
	different modes may require different tasks
	create methods as required for different modes, then call the correct method in ps_Completing()
	can be commanded to STOP, ABORT, HOLD, or SUSPEND at any point
COMPLETING - process complete, move product out of system and finish transition to COMPLETED
*)

IF //abort at machine error
	//insertionLeft.error OR 
	insertionRight.error OR 
	robotLeft.error OR 
	robotRight.error OR
	wrapper.error
THEN
	pmlCommand := ePMLCommand_Abort;
	
ELSIF stop THEN //stop at command stop
	pmlCommand := ePMLCommand_Stop;

ELSIF FALSE (*A2.1 cannot allow bundles to enter*) THEN //FALSE condition never executes - this is temporary
	pmlCommand := ePMLCommand_Suspend;
END_IF


CASE pmlState OF
	0: (*ePMLState_Undefined*) //default state on startup
		pmlCommand := ePMLCommand_Stop;
		
	ePMLState_Stopping:
		IF ps_Stopping() THEN
			pmlStateMachine.M_StateComplete();
		END_IF
		
	ePMLState_Stopped:
		pmlCommand := ePMLCommand_Reset;
	
    ePMLState_Resetting:
		IF ps_Resetting() THEN
			reset := FALSE;
			pmlStateMachine.M_StateComplete();
		END_IF
		
	ePMLState_Idle:
		IF execute THEN
			execute := FALSE;
			pmlCommand := ePMLCommand_Start;
		END_IF		
	
	ePMLState_Starting:
		IF ps_Starting() THEN
			pmlStateMachine.M_StateComplete();
		END_IF
	
	ePMLState_Execute: 
		IF hold THEN
			pmlCommand := ePMLCommand_Hold;
		END_IF
		
		IF ps_Execute(error => error) THEN
			pmlStateMachine.M_StateComplete();
			pmlCommand := ePMLCommand_Complete;
		END_IF
		
	ePMLState_Completing:
		pmlStateMachine.M_StateComplete();
	
	ePMLState_Complete:
		pmlCommand := ePMLCommand_Reset;
	
	ePMLState_Holding:
		IF ps_Holding() THEN
			pmlStateMachine.M_StateComplete();
		END_IF
	
	ePMLState_Held:
		IF NOT hold THEN
			pmlCommand := ePMLCommand_Unhold;
		END_IF
	
	ePMLState_Unholding:
		pmlStateMachine.M_StateComplete(); //release all pause commands and IO
	
	ePMLState_Suspended: //based on output section conditions
	ePMLState_Suspending: //based on output section conditions
	ePMLState_Unsuspending: //based on output section conditions
	
	ePMLState_Aborting:
		IF ps_Aborting() THEN
			pmlStateMachine.M_StateComplete();
		END_IF
	
	ePMLState_Aborted:
		pmlCommand := ePMLCommand_Clear;
	
	ePMLState_Clearing:
		IF ps_Clearing() THEN
			pmlStateMachine.M_StateComplete();
		END_IF
	
END_CASE]]></ST>
      </Implementation>
    </Action>
    <Action Name="stopSequence" Id="{acdc0711-6542-4403-a9a7-c5cefe95a89f}" FolderPath="Actions\">
      <Implementation>
        <ST><![CDATA[insertionLeft.stop();
insertionRight.stop();
pistonBottom.stop();

robotLeft.clearCommand();
robotRight.clearCommand();]]></ST>
      </Implementation>
    </Action>
    <LineIds Name="CarCorEx">
      <LineId Id="990" Count="0" />
      <LineId Id="1333" Count="0" />
      <LineId Id="1332" Count="0" />
      <LineId Id="1349" Count="0" />
      <LineId Id="1335" Count="0" />
      <LineId Id="1334" Count="0" />
      <LineId Id="991" Count="1" />
      <LineId Id="998" Count="4" />
      <LineId Id="1005" Count="0" />
      <LineId Id="1209" Count="0" />
      <LineId Id="1006" Count="0" />
      <LineId Id="1350" Count="0" />
    </LineIds>
    <LineIds Name="CarCorEx.callLocalModules">
      <LineId Id="2" Count="22" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="CarCorEx.configPML">
      <LineId Id="28" Count="24" />
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="CarCorEx.homingSequence">
      <LineId Id="2" Count="1" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="CarCorEx.load">
      <LineId Id="457" Count="0" />
      <LineId Id="460" Count="0" />
      <LineId Id="327" Count="1" />
      <LineId Id="440" Count="0" />
      <LineId Id="442" Count="1" />
      <LineId Id="602" Count="0" />
      <LineId Id="601" Count="0" />
      <LineId Id="603" Count="1" />
      <LineId Id="488" Count="0" />
      <LineId Id="487" Count="0" />
      <LineId Id="665" Count="1" />
      <LineId Id="671" Count="0" />
      <LineId Id="673" Count="8" />
      <LineId Id="672" Count="0" />
      <LineId Id="682" Count="0" />
      <LineId Id="684" Count="8" />
      <LineId Id="683" Count="0" />
      <LineId Id="693" Count="1" />
      <LineId Id="696" Count="0" />
      <LineId Id="695" Count="0" />
      <LineId Id="669" Count="0" />
      <LineId Id="667" Count="0" />
      <LineId Id="489" Count="0" />
      <LineId Id="594" Count="0" />
      <LineId Id="629" Count="0" />
      <LineId Id="643" Count="0" />
      <LineId Id="653" Count="0" />
      <LineId Id="630" Count="0" />
      <LineId Id="560" Count="0" />
      <LineId Id="644" Count="0" />
      <LineId Id="650" Count="0" />
      <LineId Id="562" Count="1" />
      <LineId Id="645" Count="0" />
      <LineId Id="651" Count="0" />
      <LineId Id="566" Count="0" />
      <LineId Id="568" Count="0" />
      <LineId Id="646" Count="0" />
      <LineId Id="652" Count="0" />
      <LineId Id="561" Count="0" />
      <LineId Id="631" Count="0" />
      <LineId Id="504" Count="0" />
      <LineId Id="518" Count="0" />
      <LineId Id="524" Count="0" />
      <LineId Id="526" Count="0" />
      <LineId Id="525" Count="0" />
      <LineId Id="647" Count="0" />
      <LineId Id="523" Count="0" />
      <LineId Id="505" Count="2" />
      <LineId Id="527" Count="2" />
      <LineId Id="648" Count="0" />
      <LineId Id="531" Count="0" />
      <LineId Id="508" Count="0" />
      <LineId Id="510" Count="0" />
      <LineId Id="490" Count="0" />
    </LineIds>
    <LineIds Name="CarCorEx.loadCornerCardboards">
      <LineId Id="1472" Count="0" />
      <LineId Id="1580" Count="0" />
      <LineId Id="1579" Count="0" />
      <LineId Id="1582" Count="8" />
      <LineId Id="1581" Count="0" />
      <LineId Id="1592" Count="0" />
      <LineId Id="1594" Count="8" />
      <LineId Id="1593" Count="0" />
      <LineId Id="1603" Count="1" />
      <LineId Id="1577" Count="0" />
      <LineId Id="1576" Count="0" />
      <LineId Id="1473" Count="87" />
      <LineId Id="5" Count="0" />
      <LineId Id="1578" Count="0" />
    </LineIds>
    <LineIds Name="CarCorEx.loadCornerCardboardsEx">
      <LineId Id="921" Count="0" />
      <LineId Id="1111" Count="8" />
      <LineId Id="1194" Count="0" />
      <LineId Id="1121" Count="17" />
      <LineId Id="1199" Count="2" />
      <LineId Id="1139" Count="14" />
      <LineId Id="1202" Count="2" />
      <LineId Id="1154" Count="14" />
      <LineId Id="1205" Count="2" />
      <LineId Id="1169" Count="15" />
      <LineId Id="1208" Count="0" />
      <LineId Id="1210" Count="0" />
      <LineId Id="1209" Count="0" />
      <LineId Id="1185" Count="8" />
      <LineId Id="1110" Count="0" />
    </LineIds>
    <LineIds Name="CarCorEx.loadCornerGuards">
      <LineId Id="6" Count="0" />
      <LineId Id="88" Count="0" />
      <LineId Id="87" Count="0" />
      <LineId Id="90" Count="8" />
      <LineId Id="89" Count="0" />
      <LineId Id="109" Count="0" />
      <LineId Id="100" Count="8" />
      <LineId Id="99" Count="0" />
      <LineId Id="110" Count="1" />
      <LineId Id="84" Count="0" />
      <LineId Id="83" Count="0" />
      <LineId Id="7" Count="65" />
      <LineId Id="5" Count="0" />
      <LineId Id="85" Count="0" />
    </LineIds>
    <LineIds Name="CarCorEx.loadCornerGuardsEx">
      <LineId Id="6" Count="0" />
      <LineId Id="109" Count="6" />
      <LineId Id="23" Count="0" />
      <LineId Id="224" Count="0" />
      <LineId Id="5" Count="0" />
      <LineId Id="118" Count="3" />
      <LineId Id="191" Count="0" />
      <LineId Id="193" Count="12" />
      <LineId Id="192" Count="0" />
      <LineId Id="206" Count="0" />
      <LineId Id="210" Count="6" />
      <LineId Id="225" Count="0" />
      <LineId Id="218" Count="3" />
      <LineId Id="223" Count="0" />
      <LineId Id="207" Count="0" />
      <LineId Id="122" Count="14" />
      <LineId Id="152" Count="14" />
      <LineId Id="182" Count="7" />
      <LineId Id="116" Count="0" />
    </LineIds>
    <LineIds Name="CarCorEx.loadFlatCardboards">
      <LineId Id="108" Count="0" />
      <LineId Id="192" Count="0" />
      <LineId Id="191" Count="0" />
      <LineId Id="194" Count="8" />
      <LineId Id="193" Count="0" />
      <LineId Id="204" Count="0" />
      <LineId Id="206" Count="8" />
      <LineId Id="205" Count="0" />
      <LineId Id="215" Count="1" />
      <LineId Id="189" Count="0" />
      <LineId Id="188" Count="0" />
      <LineId Id="116" Count="15" />
      <LineId Id="115" Count="0" />
      <LineId Id="132" Count="0" />
      <LineId Id="35" Count="1" />
      <LineId Id="134" Count="1" />
      <LineId Id="171" Count="0" />
      <LineId Id="137" Count="1" />
      <LineId Id="133" Count="0" />
      <LineId Id="139" Count="0" />
      <LineId Id="141" Count="10" />
      <LineId Id="140" Count="0" />
      <LineId Id="44" Count="1" />
      <LineId Id="152" Count="1" />
      <LineId Id="172" Count="0" />
      <LineId Id="155" Count="14" />
      <LineId Id="176" Count="0" />
      <LineId Id="170" Count="0" />
      <LineId Id="54" Count="4" />
      <LineId Id="7" Count="0" />
      <LineId Id="178" Count="0" />
      <LineId Id="177" Count="0" />
      <LineId Id="190" Count="0" />
    </LineIds>
    <LineIds Name="CarCorEx.loadFlatCardboardsEx">
      <LineId Id="280" Count="81" />
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="CarCorEx.maintenance">
      <LineId Id="12" Count="0" />
      <LineId Id="5" Count="2" />
      <LineId Id="9" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="10" Count="1" />
    </LineIds>
    <LineIds Name="CarCorEx.process">
      <LineId Id="274" Count="0" />
      <LineId Id="276" Count="0" />
      <LineId Id="278" Count="1" />
      <LineId Id="284" Count="2" />
      <LineId Id="277" Count="0" />
      <LineId Id="275" Count="0" />
      <LineId Id="108" Count="7" />
      <LineId Id="288" Count="1" />
      <LineId Id="291" Count="0" />
      <LineId Id="290" Count="0" />
      <LineId Id="244" Count="9" />
      <LineId Id="255" Count="0" />
      <LineId Id="242" Count="0" />
      <LineId Id="254" Count="0" />
      <LineId Id="116" Count="2" />
      <LineId Id="256" Count="0" />
      <LineId Id="125" Count="0" />
      <LineId Id="292" Count="2" />
      <LineId Id="258" Count="11" />
      <LineId Id="257" Count="0" />
      <LineId Id="270" Count="0" />
      <LineId Id="207" Count="2" />
      <LineId Id="133" Count="1" />
      <LineId Id="236" Count="0" />
      <LineId Id="238" Count="0" />
      <LineId Id="272" Count="0" />
      <LineId Id="241" Count="0" />
      <LineId Id="235" Count="0" />
      <LineId Id="239" Count="0" />
      <LineId Id="273" Count="0" />
      <LineId Id="240" Count="0" />
      <LineId Id="271" Count="0" />
      <LineId Id="135" Count="9" />
      <LineId Id="149" Count="57" />
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="CarCorEx.ps_Aborting">
      <LineId Id="6" Count="3" />
      <LineId Id="25" Count="0" />
      <LineId Id="33" Count="6" />
      <LineId Id="24" Count="0" />
      <LineId Id="10" Count="10" />
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="CarCorEx.ps_Clearing">
      <LineId Id="14" Count="0" />
      <LineId Id="6" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="7" Count="0" />
      <LineId Id="5" Count="0" />
      <LineId Id="9" Count="4" />
    </LineIds>
    <LineIds Name="CarCorEx.ps_Execute">
      <LineId Id="18" Count="4" />
      <LineId Id="28" Count="0" />
      <LineId Id="10" Count="0" />
    </LineIds>
    <LineIds Name="CarCorEx.ps_Holding">
      <LineId Id="10" Count="0" />
      <LineId Id="6" Count="3" />
      <LineId Id="15" Count="0" />
      <LineId Id="14" Count="0" />
      <LineId Id="16" Count="1" />
    </LineIds>
    <LineIds Name="CarCorEx.ps_Resetting">
      <LineId Id="15" Count="0" />
      <LineId Id="7" Count="3" />
      <LineId Id="19" Count="0" />
      <LineId Id="11" Count="3" />
      <LineId Id="6" Count="0" />
    </LineIds>
    <LineIds Name="CarCorEx.ps_Starting">
      <LineId Id="16" Count="0" />
      <LineId Id="6" Count="4" />
      <LineId Id="5" Count="0" />
      <LineId Id="12" Count="0" />
      <LineId Id="11" Count="0" />
      <LineId Id="13" Count="2" />
    </LineIds>
    <LineIds Name="CarCorEx.ps_Stopping">
      <LineId Id="20" Count="0" />
      <LineId Id="6" Count="2" />
      <LineId Id="40" Count="2" />
      <LineId Id="44" Count="0" />
      <LineId Id="43" Count="0" />
      <LineId Id="45" Count="0" />
      <LineId Id="32" Count="2" />
      <LineId Id="9" Count="2" />
      <LineId Id="48" Count="0" />
      <LineId Id="47" Count="0" />
      <LineId Id="12" Count="3" />
      <LineId Id="24" Count="3" />
      <LineId Id="5" Count="0" />
      <LineId Id="46" Count="0" />
    </LineIds>
    <LineIds Name="CarCorEx.runPML">
      <LineId Id="533" Count="55" />
      <LineId Id="664" Count="0" />
      <LineId Id="589" Count="5" />
      <LineId Id="596" Count="1" />
      <LineId Id="604" Count="1" />
      <LineId Id="668" Count="1" />
      <LineId Id="667" Count="0" />
      <LineId Id="617" Count="1" />
      <LineId Id="661" Count="2" />
      <LineId Id="677" Count="0" />
      <LineId Id="619" Count="40" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="CarCorEx.stopSequence">
      <LineId Id="2" Count="4" />
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>